[tools]
rojo = { github = "rojo-rbx/rojo", version = "7.3.0" }
wally = { source = "UpliftGames/wally", version = "0.3.1" }
selene = { source = "Kampfkarren/selene", version = "0.25.0" }
stylua = { source = "JohnnyMorganz/StyLua", version = "0.17.1"}